services:
  web:
    build:
      context: .
    command: bash -c "python manage.py runserver 0.0.0.0:${WEB_PORT}"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:16.2
    volumes:
      - django_auth_system_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  redis:
    image: redis:alpine

  worker_default:
    restart: unless-stopped
    build:
      context: .
    command: celery -A core worker --loglevel=info --queues=default --concurrency=2 # 2 workers for default
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  django_auth_system_db:
  